source ~/.profile

shopt -s globstar # allow **/*.py to work

export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
shopt -s histappend                      # append to history, don't overwrite it
shopt -s histreedit # reedit a history substitution line if it failed
shopt -s histverify # edit a recalled history line before executing
powerline-daemon
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python3*/site-packages/powerline/bindings/bash/powerline.sh



for f in /etc/bash_completion.d/*; do
   source $f
done

complete -C aws_completer aws

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

#docker-machine start | grep 'Starting VM...' && docker-machine env > ~/.docker_env
#source ~/.docker_env
export PATH="/usr/local/opt/python@3.9/bin:/usr/local/opt/python@3.8/bin:~/Library/Python/2.7/bin:/usr/local/sbin:$PATH"
eval "$(hub alias -s)"
ssh-add -k .ssh/ocono_rsa

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export ANSIBLE_SSH_PIPELINING=1
export ANSIBLE_FORKS=25
alias ansible='ansible -i ~/ec2.py -u ubuntu'
alias deploy='git push --atomic origin $(git branch --show-current) $(git describe --tags)'
ssh-add --apple-use-keychain ~/.ssh/id_rsa
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)


# Setting PATH for Python 3.9
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}"
export PATH

# Setting PATH for Python 3.10
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH
