source ~/.profile

shopt -s globstar # allow **/*.py to work

export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
shopt -s histappend                      # append to history, don't overwrite it
shopt -s histreedit # reedit a history substitution line if it failed
shopt -s histverify # edit a recalled history line before executing
powerline-daemon
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python3.4/site-packages/powerline/bindings/bash/powerline.sh



for f in /etc/bash_completion.d/*; do
   source $f
done

complete -C '/usr/local/bin/aws_completer' aws

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

#docker-machine start | grep 'Starting VM...' && docker-machine env > ~/.docker_env
#source ~/.docker_env
export PATH="/usr/local/sbin:$PATH"

