#!/bin/bash

dotfiles=~/dotfiles/dotfiles
if [ "$1" ==  "-f" ]
then 
    force='f'
else
    force=''
fi

for file in `ls $dotfiles`
do
    if [ -d $dotfiles/$file ] && [ -e ~/.$file ]
    then
        echo "will not recreate symlink for directory .$file"
    else
        ln -s$force $dotfiles/$file ~/.$file
    fi
done

sudo mkdir -p /etc/bash_completion.d
sudo ln -s ~/dotfiles/bash_completion/fabric-bash-autocompletion/fab /etc/bash_completion.d/fab
sudo ln -s ~/dotfiles/bash_completion/vagrant-bash-completion/vagrant /etc/bash_completion.d/vagrant
sudo ln -s ~/dotfiles/bash_completion/git-devbliss /etc/bash_completion.d/git-devbliss
sudo ln -s ~/dotfiles/ssh_config ~/.ssh/config
mkdir -p ~/bin
sudo ln -s /opt/local/bin/ack-5.12 ~/bin/ack
