#! /bin/sh

which brew > /dev/null || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

taps="
homebrew/php
"
programs="
reattach-to-user-namespace
curl
bash
bash-completion
caskroom/cask/brew-cask
git
git-lfs
hub
htop-osx
python
python3
ruby
tree
wget
ngrep
openssl
readline
ctags
jq
go
mercurial
ack
terminal-notifier
watch
tmux
npm
php56
php56-xdebug
composer
neovim
"
head_programs="
"

casks="
skype
vagrant
virtualbox
seil
karabiner
iterm2
hammerspoon
sequel-pro
github-desktop
chefdk
"

brew update
brew tap $taps 2>&1 | grep -v 'Warning: Already tapped'
brew install $programs 2>&1 | grep -v 'Warning:.*already installed'
brew install --HEAD $head_programs 2>&1 | grep -v 'Warning:.*already installed'
fzf --version || brew install fzf && $(brew --prefix)/opt/fzf/install
brew cask install $casks 2>&1 | grep -v 'Warning:.*already installed'
brew upgrade
brew cleanup
brew cask cleanup
