#! /bin/sh

if [ -x /opt/local/bin/port ]
then
    sudo port selfupdate
    sudo port install \
    iTerm2 `# better terminal` \
    curl `# call url` \
    bash `# newer bash` \
    git-core +bash_completion `# git with autocompletion` \
    git-devbliss `# devbliss git-extensions` \
    htop `# show running process (human readable)` \
    python27 `# python 2.7` \
    py27-pip `# python 2.7 package manager` \
    py27-setuptools `# easy_install` \
    python33 `# python 3.3` \
    py33-setuptools `# easy_install` \
    py33-pip `# python 3.3 package manager` \
    py33-ipython `# interactive python` \
    ruby `# programming language` \
    rb19-bundler `# ruby package manager` \
    rsync `# sync files with remote location` \
    tree `# show content of directory as tree` \
    wget `# download` \
    ngrep `# network grep` \
    macvim `# vi with gui` \
    python_select `# select what is python` \
    ipython_select `# select what is ipython` \
    openssl `# newer openssl` \
    readline `# commandline editing` \
    ctags `# exuberant ctags` \
    jq `# json parser for bash` \
    puppet `# puppet`

    sudo port select python python27 # compatibility
    sudo port select ipython ipython33
    sudo port upgrade outdated
else
    macports_pkg=MacPorts-2.2.1-10.9-Mavericks.pkg
    open https://distfiles.macports.org/MacPorts/$macports_pkg
    sleep 5
    open ~/Downloads/$macports_pkg
    echo 'please install macports and then re-run this script'
    echo "add the following two lines to your profile:\nexport C_INCLUDE_PATH=/opt/local/include\nexport LIBRARY_PATH=/opt/local/lib"
fi
