#! /bin/sh

which brew > /dev/null || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

taps="
homebrew/php
homebrew/cask-fonts
"
programs="
reattach-to-user-namespace
curl
bash
bash-completion
caskroom/cask/brew-cask
git
git-lfs
hub
htop-osx
python
python3
ruby
tree
wget
ngrep
openssl
readline
jq
go
ack
terminal-notifier
watch
tmux
npm
node
php56
php56-xdebug
composer
neovim
entr
gh
yarn
code-minimap
"
head_programs="
universal-ctags/universal-ctags/universal-ctags
"

casks="
iterm2
hammerspoon
font-inconsolata-go-nerd-font
"

brew update
brew tap $taps 2>&1 | grep -v 'Warning: Already tapped'
brew install $programs 2>&1 | grep -v 'Warning:.*already installed'
brew install --HEAD $head_programs 2>&1 | grep -v 'Warning:.*already installed'
fzf --version || brew install fzf && $(brew --prefix)/opt/fzf/install
brew cask install $casks 2>&1 | grep -v 'Warning:.*already installed'
brew upgrade
brew cleanup
brew cask cleanup
